#!/usr/bin/env ruby

require_relative '../lib/fradium'

=begin
        check username        # check if username exists
        create username       # create new user and password
        show username         # show password for username
        showall               # show all users
        showactive            # show active (enabled) users
        showinactive          # show inactive (disabled) users
        modify username       # generate new password for username
        modifyguest username  # generate new guest password for username
        disable username      # disable the user
        dbconsole             # enter database console
=end

SUBCOMMANDS = %{dbconsole}

@f = Fradium.new(host: :localhost, username: :root, database: :new_radius)

def help
  print <<"EOD"
usage:
  create <username>                   # create new user with password
  show <username>                     # show password for username
  showall                             # show all users
  expire <username>                   # expire the user right now
  unexpire <username>                 # unexpire the user
  setexpire <username> <expiry date>  # set expiry date (date must be parseable by Time#parse)
  modify <username>                   # generate new password for username
  dbconsole                           # enter database console
EOD
  exit
end

def show_user(username)
  user = @f.find_user(username).first
  printf "%s  %s\n", user['username'], user['value']
end

case ARGV[0]

when 'create'
  help if ARGV[1]&.empty?
  @f.create_user(ARGV[1])
  show_user(ARGV[1])

when 'dbconsole'
  @f.dbconsole

when 'show'
  show_user(ARGV[1])

when 'showall'
  @f.all_users.each do |e|
    puts e
  end

when 'expire'
  @f.expire_user(ARGV[1])

when 'unexpire'
  @f.unexpire_user(ARGV[1])

when 'setexpire'
  help if ARGV[2].nil? || ARGV[2].empty?
  expiry_date = Time.parse(ARGV[2])
  @f.set_expiration(ARGV[1], expiry_date)

when 'modify' # change user password
  @f.modify_user(ARGV[1])
  show_user(ARGV[1])

else # unknown subcommand
  help
end
